# Generated by Django 4.2.16 on 2024-12-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=256)),
                ('middleName', models.CharField(max_length=256)),
                ('lastName', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('skinTone', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=256)),
                ('dressing', models.TextField()),
                ('profilePhoto', models.ImageField(default='/media/parent-wife-child.png', upload_to='media/reportedChilderen')),
                ('status', models.CharField(default='pending', max_length=256)),
            ],
        ),
    ]
